const COMPANY = '6309581410'
const DOMAIN = 'ukviservices.co.uk'
const REGISTERED_OFFICE = 'BANDLAGUDA KHALSA, Hyderabad'

export const POLICY_IDS = ['terms', 'privacy', 'refunds', 'returns', 'shipping']

export const POLICY_META = {
  terms: { title: 'Terms & Conditions', shortLabel: 'Terms' },
  privacy: { title: 'Privacy Policy', shortLabel: 'Privacy' },
  refunds: { title: 'Refund & Cancellation Policy', shortLabel: 'Refunds' },
  returns: { title: 'Return Policy', shortLabel: 'Returns' },
  shipping: { title: 'Shipping Policy', shortLabel: 'Shipping' },
}

function Section({ title, children }) {
  return (
    <section className="mb-8">
      {title && <h2 className="text-lg font-bold text-[#003078] mb-3">{title}</h2>}
      <div className="text-gray-600 text-sm leading-relaxed space-y-3">{children}</div>
    </section>
  )
}

function P({ children, className = '' }) {
  return <p className={className}>{children}</p>
}

function List({ items }) {
  return (
    <ol className="list-decimal list-inside space-y-2 pl-1">
      {items.map((item, i) => (
        <li key={i}>{item}</li>
      ))}
    </ol>
  )
}

function TermsContent() {
  return (
    <>
      <Section>
        <P>
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable
          and the amended provisions pertaining to electronic records in various statutes as amended by the Information
          Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or
          digital signatures.
        </P>
        <P>
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
          (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms
          of Use for access or usage of domain name {DOMAIN} (&apos;Website&apos;), including the related mobile site and mobile
          application (hereinafter referred to as &apos;Platform&apos;).
        </P>
        <P>
          The Platform is owned by {COMPANY}, a company incorporated under the Companies Act, 1956 with its registered office
          at {REGISTERED_OFFICE} (hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
        </P>
        <P>
          Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of
          Use&quot;) as applicable to the Platform including the applicable policies which are incorporated herein by way of
          reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform
          for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms
          and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use
          relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, &apos;Services&apos;).
          Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are
          expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any
          time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay
          informed of updates.
        </P>
        <P>
          For the purpose of these Terms of Use, wherever the context so requires &apos;you&apos;, &apos;your&apos; or &apos;user&apos; shall mean any
          natural or legal person who has agreed to become a user/buyer on the Platform.
        </P>
        <P className="font-semibold text-gray-700">
          ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER
          THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
        </P>
      </Section>

      <Section title="Terms of Use">
        <List
          items={[
            'To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.',
            'Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.',
            'Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.',
            'The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.',
            'You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.',
            'You agree to pay us the charges associated with availing the Services.',
            'You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.',
            'You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.',
            'You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.',
            'You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney\'s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.',
            'Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.',
            'These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.',
            `All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in ${REGISTERED_OFFICE}, India.`,
            'All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.',
          ]}
        />
      </Section>
    </>
  )
}

function PrivacyContent({ config }) {
  return (
    <>
      <Section title="Introduction">
        <P>
          This Privacy Policy describes how {COMPANY} and its affiliates (collectively &quot;{COMPANY}, we, our, us&quot;) collect, use,
          share, protect or otherwise process your information/ personal data through our website {DOMAIN} (hereinafter
          referred to as Platform). Please note that you may be able to browse certain sections of the Platform without
          registering with us. We do not offer any product/service under this Platform outside India and your personal data will
          primarily be stored and processed in India. By visiting this Platform, providing your information or availing any
          product/service offered on the Platform, you expressly agree to be bound by the terms and conditions of this Privacy
          Policy, the Terms of Use and the applicable service/product terms and conditions, and agree to be governed by the
          laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree
          please do not use or access our Platform.
        </P>
      </Section>

      <Section title="Collection">
        <P>
          We collect your personal data when you use our Platform, services or otherwise interact with us during the course of
          our relationship and related information provided from time to time. Some of the information that we may collect
          includes but is not limited to personal data / information provided to us during sign-up/registering or using our
          Platform such as name, date of birth, address, telephone/mobile number, email ID and/or any such information shared
          as proof of identity or address. Some of the sensitive personal data may be collected with your consent, such as your
          bank account or credit or debit card or other payment instrument information or biometric information such as your
          facial features or physiological information (in order to enable use of certain features when opted for, available on
          the Platform) etc all of the above being in accordance with applicable law(s). You always have the option to not
          provide information, by choosing not to use a particular service or feature on the Platform. We may track your
          behaviour, preferences, and other information that you choose to provide on our Platform. This information is
          compiled and analysed on an aggregated basis. We will also collect your information related to your transactions on
          Platform and such third-party business partner platforms. When such a third-party business partner collects your
          personal data directly from you, you will be governed by their privacy policies. We shall not be responsible for the
          third-party business partner&apos;s privacy practices or the content of their privacy policies, and we request you to read
          their privacy policies prior to disclosing any information. If you receive an email, a call from a person/association
          claiming to be {COMPANY} seeking any personal data like debit/credit card PIN, net-banking or mobile banking password,
          we request you to never provide such information. If you have already revealed such information, report it immediately
          to an appropriate law enforcement agency.
        </P>
      </Section>

      <Section title="Usage">
        <P>
          We use personal data to provide the services you request. To the extent we use your personal data to market to you, we
          will provide you the ability to opt-out of such uses. We use your personal data to assist sellers and business partners
          in handling and fulfilling orders; enhancing customer experience; to resolve disputes; troubleshoot problems; inform
          you about online and offline offers, products, services, and updates; customise your experience; detect and protect us
          against error, fraud and other criminal activity; enforce our terms and conditions; conduct marketing research, analysis
          and surveys; and as otherwise described to you at the time of collection of information. You understand that your
          access to these products/services may be affected in the event permission is not provided to us.
        </P>
      </Section>

      <Section title="Sharing">
        <P>
          We may share your personal data internally within our group entities, our other corporate entities, and affiliates to
          provide you access to the services and products offered by them. These entities and affiliates may market to you as a
          result of such sharing unless you explicitly opt-out. We may disclose personal data to third parties such as sellers,
          business partners, third party service providers including logistics partners, prepaid payment instrument issuers,
          third-party reward programs and other payment opted by you. These disclosure may be required for us to provide you
          access to our services and products offered to you, to comply with our legal obligations, to enforce our user
          agreement, to facilitate our marketing and advertising activities, to prevent, detect, mitigate, and investigate
          fraudulent or illegal activities related to our services. We may disclose personal and sensitive personal data to
          government agencies or other authorised law enforcement agencies if required to do so by law or in the good faith
          belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We
          may disclose personal data to law enforcement offices, third party rights owners, or others in the good faith belief
          that such disclosure is reasonably necessary to: enforce our Terms of Use or Privacy Policy; respond to claims that an
          advertisement, posting or other content violates the rights of a third party; or protect the rights, property or
          personal safety of our users or the general public.
        </P>
      </Section>

      <Section title="Security Precautions">
        <P>
          To protect your personal data from unauthorised access or disclosure, loss or misuse we adopt reasonable security
          practices and procedures. Once your information is in our possession or whenever you access your account information, we
          adhere to our security guidelines to protect it against unauthorised access and offer the use of a secure server.
          However, the transmission of information is not completely secure for reasons beyond our control. By using the
          Platform, the users accept the security implications of data transmission over the internet and the World Wide Web
          which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks
          regarding use of the Platform. Users are responsible for ensuring the protection of login and password records for
          their account.
        </P>
      </Section>

      <Section title="Data Deletion and Retention">
        <P>
          You have an option to delete your account by visiting your profile and settings on our Platform, this action would
          result in you losing all information related to your account. You may also write to us at the contact information
          provided below to assist you with these requests. We may in event of any pending grievance, claims, pending shipments
          or any other services we may refuse or delay deletion of the account. Once the account is deleted, you will lose
          access to the account. We retain your personal data information for a period no longer than is required for the purpose
          for which it was collected or as required under any applicable law. However, we may retain data related to you if we
          believe it may be necessary to prevent fraud or future abuse or for other legitimate purposes. We may continue to
          retain your data in anonymised form for analytical and research purposes.
        </P>
      </Section>

      <Section title="Your Rights">
        <P>
          You may access, rectify, and update your personal data directly through the functionalities provided on the Platform.
        </P>
      </Section>

      <Section title="Consent">
        <P>
          By visiting our Platform or by providing your information, you consent to the collection, use, storage, disclosure and
          otherwise processing of your information on the Platform in accordance with this Privacy Policy. If you disclose to us any
          personal data relating to other people, you represent that you have the authority to do so and permit us to use the
          information in accordance with this Privacy Policy. You, while providing your personal data over the Platform or any
          partner platforms or establishments, consent to us (including our other corporate entities, affiliates, lending
          partners, technology partners, marketing channels, business partners and other third parties) to contact you through
          SMS, instant messaging apps, call and/or e-mail for the purposes specified in this Privacy Policy. You have an option
          to withdraw your consent that you have already provided by writing to the Grievance Officer at the contact information
          provided below. Please mention &quot;Withdrawal of consent for processing personal data&quot; in your subject line of your
          communication. We may verify such requests before acting on our request. However, please note that your withdrawal of
          consent will not be retrospective and will be in accordance with the Terms of Use, this Privacy Policy, and
          applicable laws. In the event you withdraw consent given to us under this Privacy Policy, we reserve the right to
          restrict or deny the provision of our services for which we consider such information to be necessary.
        </P>
      </Section>

      <Section title="Changes to this Privacy Policy">
        <P>
          Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our
          information practices. We may alert / notify you about the significant changes to the Privacy Policy, in the manner as
          may be required under applicable laws.
        </P>
      </Section>

      <Section title="Grievance Officer">
        <P><strong>Company:</strong> {COMPANY}</P>
        <P><strong>Registered Office:</strong> {REGISTERED_OFFICE}</P>
        <P><strong>Email:</strong> {config?.contact_email || 'support@ukviservices.co.uk'}</P>
        <P><strong>Phone:</strong> {config?.contact_phone || '+44 20 0000 0000'}</P>
        <P><strong>Hours:</strong> Monday – Friday (9:00 – 18:00)</P>
      </Section>
    </>
  )
}

function RefundsContent() {
  return (
    <Section>
      <P>
        This refund and cancellation policy outlines how you can cancel or seek a refund for a product / service that you have
        purchased through the Platform. Under this policy:
      </P>
      <List
        items={[
          'Cancellations will only be considered if the request is made within 5 days of placing the order. However, cancellation requests may not be entertained if the orders have been communicated to such sellers / merchant(s) listed on the Platform and they have initiated the process of shipping them, or the product is out for delivery. In such an event, you may choose to reject the product at the doorstep.',
          `${COMPANY} does not accept cancellation requests for perishable items like flowers, eatables, etc. However, the refund / replacement can be made if the user establishes that the quality of the product delivered is not good.`,
          'In case of receipt of damaged or defective items, please report to our customer service team. The request would be entertained once the seller/ merchant listed on the Platform, has checked and determined the same at its own end. This should be reported within 5 days of receipt of products. In case you feel that the product received is not as shown on the site or as per your expectations, you must bring it to the notice of our customer service within 5 days of receiving the product. The customer service team after looking into your complaint will take an appropriate decision.',
          'In case of complaints regarding the products that come with a warranty from the manufacturers, please refer the issue to them.',
          `In case of any refunds approved by ${COMPANY}, it will take 7 days for the refund to be processed to you.`,
        ]}
      />
    </Section>
  )
}

function ReturnsContent() {
  return (
    <Section>
      <P>
        We offer refund / exchange within first 10 days from the date of your purchase. If 10 days have passed since your
        purchase, you will not be offered a return, exchange or refund of any kind. In order to become eligible for a return or
        an exchange, (i) the purchased item should be unused and in the same condition as you received it, (ii) the item must
        have original packaging, (iii) if the item that you purchased on a sale, then the item may not be eligible for a return /
        exchange. Further, only such items are replaced by us (based on an exchange request), if such items are found defective
        or damaged.
      </P>
      <P>
        You agree that there may be a certain category of products / items that are exempted from returns or refunds. Such
        categories of the products would be identified to you at the item of purchase. For exchange / return accepted request(s)
        (as applicable), once your returned product / item is received and inspected by us, we will send you an email to
        notify you about receipt of the returned / exchanged product. Further, if the same has been approved after the quality
        check at our end, your request (i.e. return / exchange) will be processed in accordance with our policies.
      </P>
    </Section>
  )
}

function ShippingContent() {
  return (
    <Section>
      <P>
        The orders for the user are shipped through registered domestic courier companies and/or speed post only. Orders are
        shipped within 15 days from the date of the order and/or payment or as per the delivery date agreed at the time of order
        confirmation and delivering of the shipment, subject to courier company / post office norms. Platform Owner shall not
        be liable for any delay in delivery by the courier company / postal authority. Delivery of all orders will be made to the
        address provided by the buyer at the time of purchase. Delivery of our services will be confirmed on your email ID as
        specified at the time of registration. If there are any shipping cost(s) levied by the seller or the Platform Owner (as
        the case be), the same is not refundable.
      </P>
    </Section>
  )
}

const CONTENT_MAP = {
  terms: TermsContent,
  privacy: PrivacyContent,
  refunds: RefundsContent,
  returns: ReturnsContent,
  shipping: ShippingContent,
}

export function PolicyPage({ page, config, onNavigate }) {
  const meta = POLICY_META[page]
  const Content = CONTENT_MAP[page]

  if (!meta || !Content) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="text-center">
          <p className="text-gray-500 mb-4">Policy not found.</p>
          <button onClick={() => onNavigate('home')} className="text-[#003078] font-semibold hover:underline">
            ← Back to Home
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-[#003078] text-white py-4 px-4 shadow">
        <div className="max-w-4xl mx-auto flex items-center justify-between gap-4">
          <button onClick={() => onNavigate('home')} className="flex items-center gap-2 hover:opacity-90 transition">
            <div className="bg-[#f3a712] rounded-full w-9 h-9 flex items-center justify-center font-bold text-[#003078] text-sm">UK</div>
            <span className="font-bold hidden sm:inline">{config?.site_name || 'UKVI Services'}</span>
          </button>
          <button onClick={() => onNavigate('home')} className="text-sm text-blue-200 hover:text-white transition">
            ← Back to Home
          </button>
        </div>
      </header>

      <div className="max-w-4xl mx-auto py-10 px-4">
        <div className="flex flex-col lg:flex-row gap-8">
          <aside className="lg:w-56 shrink-0">
            <nav className="bg-white rounded-2xl shadow border border-gray-100 p-4 sticky top-6">
              <p className="text-xs font-bold text-gray-400 uppercase tracking-wide mb-3">Policies</p>
              <ul className="space-y-1">
                {POLICY_IDS.map((id) => (
                  <li key={id}>
                    <button
                      onClick={() => onNavigate(id)}
                      className={`w-full text-left text-sm px-3 py-2 rounded-lg transition ${
                        id === page
                          ? 'bg-[#003078] text-white font-semibold'
                          : 'text-gray-600 hover:bg-gray-50 hover:text-[#003078]'
                      }`}
                    >
                      {POLICY_META[id].shortLabel}
                    </button>
                  </li>
                ))}
              </ul>
            </nav>
          </aside>

          <main className="flex-1 bg-white rounded-2xl shadow border border-gray-100 p-6 md:p-10">
            <h1 className="text-2xl md:text-3xl font-extrabold text-[#003078] mb-2">{meta.title}</h1>
            <p className="text-xs text-gray-400 mb-8">Last updated: June 2025</p>
            <Content config={config} />
          </main>
        </div>
      </div>

      <footer className="bg-[#001a4d] text-blue-300 text-center text-xs py-6 px-4">
        © {new Date().getFullYear()} {config?.site_name || 'UKVI Services'}. All rights reserved.
      </footer>
    </div>
  )
}
